name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android/setup-sdk@v1
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 25.1.8937393

      - name: Install Android Tools
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34"

      - name: Build Plugins
        run: |
          cd src
          chmod +x gradlew
          ./gradlew clean make makePluginsJson
