name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "src"

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          jdk-version: 17
          api-level: 30
          build-tools: 30.0.3

      - name: Build Plugins
        run: |
          cd src
          chmod +x gradlew
          ./gradlew clean make makePluginsJson

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            src/**/*.cs3
            src/build/plugins.json
